### ISSUE TITLE
доработка по v0.2.0

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-FRONT#213]
- [x] Удаление аватара
- [x] При редактировании картинки изменять ее 
- [x] обновление стопорится из-за пароля

все блокается от бэка

**Comment by IvanShish** [comment]
вообще ничего не блокается, на бэке красавчики сидят

**Comment by IvanShish** [comment]
А вот на фронте есть проблема - нет звездочек возле полей:
![image](https://github.com/FEBFES/FF-TM-FRONT/assets/42907301/327cb7d1-4644-433f-85e4-06dd9db3a79d)

Ведь у нас обязательные поля - это только email, username, password

И также нет редактирования пароля
