### ISSUE TITLE
Удаление файлов

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-FRONT#240]
На удаление вложений в таске есть этот метод:
![image](https://github.com/FEBFES/FF-TM-FRONT/assets/42907301/6570a790-56c7-42fe-b3a5-4c995db4a214)

На удаление картинок пользователя этот:
![image](https://github.com/FEBFES/FF-TM-FRONT/assets/42907301/bcfa27ab-1411-46f3-8cb5-a25786141bcd)

**Comment by Sabfes** [comment]
- [ ] удаление файлов
- [ ] при удалении очистка редакса
- [ ] при добавлении доп редакс
