### ISSUE TITLE
При наведении на кнопки добавить всплывающий текст

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-FRONT#245]
К примеру здесь: 
![image](https://github.com/FEBFES/FF-TM-FRONT/assets/42907301/acf9956b-c8a9-4d0f-93b5-ae5a047cb722)

Я вот не понимаю в чем разница между крестиком и корзиной. Было бы удобно, если бы был текст всплывающий, когда наводишься на кнопку

**Comment by Sabfes** [comment]
вот тут согласен
