### ISSUE TITLE
Небольшой анализ фильтров со стороны фронта

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-FRONT#247]
Великому фронтендеру Денису Битаеву предлагается неповторимая возможность заставить меня переделать фильтр в более удобный для менее опытного разработчика Дениса Битаева вид. Нужно произвести небольшой анализ и выяснить, как самому лучшему фронтендеру Денису Битаеву было бы ПРОЩЕ (ведь у него мало времени, все сжирает работа в Сбере) организовать поиск по фильтру. В каком виде передавать фильтр в адресной строке. И затем создать issue никчемному и абсолютно некомпететному бэкендеру ваньке-дурачку на то, что же великий и неповторимый Денис решил. 

А именно: какое разделение будет у фильтров (& для И, | для ИЛИ??? либо можно еще запятую использовать)

Какие операторы бывают? Напоминаю нынешние: EQUAL, NOT_EQUAL, LIKE (strings), IN (dates, numbers, strings), BETWEEN (dates and numbers). Должны ли для дат быть > или < или startDate, endDate. И если второй вариант, то они должны быть включая или нет? И также ко второму варианту: правило нейминга в таком случае

В случае с оператором IN как быть?

Храни Бог наше солнышко - замечательного человека и разработчика Дениса Битаева

**Comment by Sabfes** [comment]
уже бы 10 раз успел переписать фильтры, пока писал этот реферат ебучий

**Comment by IvanShish** [comment]
мне надо понимать как нужно сделать, так что создай issue и распиши все

**Comment by Sabfes** [comment]
создал ишью и ответил на все вопроси
