### ISSUE TITLE
Добавить отображение assignee в дашбоарде

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-FRONT#305]
![image](https://github.com/FEBFES/FF-TM-FRONT/assets/42907301/dddfe07d-0020-4936-82b5-51a95ae8d538)

Добавить картинку assignee в дашбоарде

Стопорится об то, что нужен дизайн

**Comment by Sabfes** [comment]
- [ ] Заменить в карточке аватар создателя таски на assignee, если нету то ничего не отображать (как в жире)
- [ ] в модалке доп инфы при наведении на аватары создателя и ответсвенного показывать в туллтипе username + email
